### ISSUE TITLE
[BUG] Email verification links show 403 error

### ISSUE THREAD

**Issue by dylanjamesdev** [Paymenter/Paymenter#299]
Hi!

I turned on email verification and upon clicking the link (as an admin user), it gives an unauthorized page. I'm not able to disable email verification because the configuration page requires email verification on the admin panel. 

Gif: https://im.sleepdeprived.wtf/fbi/MokYYiZHDr

Looks like it's just broken for all users, I ended up making a non-admin user and tried verifying but it also failed

Image: https://media.discordapp.net/attachments/1185853568322908171/1185854649207623740/image.png?ex=65912034&is=657eab34&hm=996e5aff80febd1576af9aa06235cc7ff391623678b631c08ecb0e67e8c7e88a&=&format=webp&quality=lossless&width=1920&height=888

**Comment by CorwinDev** [comment]
Hi,
Can you try opening the file app/Http/Middleware/TrustProxies.php on your VPS (located at /var/www/paymenter) and change 
```
    protected $proxies;
```
To
```   
 protected $proxies = "*";
```

**Comment by CorwinDev** [comment]
Note for myself: Add option to enable that you're behind proxy in admin panel itself

**Comment by gps949** [comment]
Just a reminder, could this issue be fixed in the official release version? At least, the problem still persists in the Docker deployment scenario.

**Comment by gps949** [comment]
> We're currently in the process of rewrite Paymenter, when the next version comes, this feature will be included!

That's great! 
The current functionality of Paymenter is already powerful, and we can look forward to the new version being even more stable.

**Comment by dysf888** [comment]
> Hi, Can you try opening the file app/Http/Middleware/TrustProxies.php on your VPS (located at /var/www/paymenter) and change
> 
> ```
> protected $proxies;
> ```
> 
> To
> 
> ```
> protected $proxies = "*";
> ```

The problem still exists
![image](https://github.com/Paymenter/Paymenter/assets/47450409/377ac593-e14d-4e1d-8db6-66a663f3dcbe)

compose 
```
version: '3.8'
x-common:
  database:
    &db-env
    MYSQL_PASSWORD: &db-password "xxxxx"
    MYSQL_ROOT_PASSWORD: "xxxxx"
  panel:
    &pm-env
    APP_NAME: Paymenter
    APP_ENV: production
    APP_KEY: xxxxx
    APP_DEBUG: false
    APP_URL: https://xxxxxxxx
    LOG_CHANNEL: stack
    LOG_DEPRECATIONS_CHANNEL: null
    LOG_LEVEL: debug
    DB_CONNECTION: mysql
    DB_HOST: database
    DB_PORT: 3306
    DB_DATABASE: paymenter
    DB_USERNAME: paymenter
    BROADCAST_DRIVER: log
    CACHE_DRIVER: file
    FILESYSTEM_DISK: local
    QUEUE_CONNECTION: database
    SESSION_DRIVER: file
    SESSION_LIFETIME: 120
    MEMCACHED_HOST: cache

services:
  database:
    image: mariadb:10.5
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "/opt/paymenter/database:/var/lib/mysql"
    environment:
      <<: *db-env
      MYSQL_DATABASE: "paymenter"
      MYSQL_USER: "paymenter"
  cache:
    image: redis:alpine
    restart: always
  paymenter:
    image: ghcr.io/paymenter/paymenter:master
    restart: always
    links:
      - database
      - cache
    volumes:
      - "/opt/paymenter/var/:/app/var/"
      - "/opt/paymenter/logs/:/app/storage/logs"
    environment:
      <<: *pm-env
      DB_PASSWORD: *db-password
  proxy:
    image: nginx:stable-alpine3.17-slim
    restart: always
    links:
      - paymenter
    volumes:
      - "/opt/paymenter/nginx/:/etc/nginx/conf.d"
      - "/opt/paymenter/certs/:/etc/certs/"
    networks:
      default:
        ipv4_address: 172.26.99.99
networks:
  default:
    ipam:
      config:
        - subnet: 172.26.99.0/24
```
zerotruet:
![image](https://github.com/Paymenter/Paymenter/assets/47450409/a2e1f2a3-16dd-4ece-9f76-3f6c4a6350cf)
